### PR TITLE
bump coverage

### PR DESCRIPTION
**Pull request by t-bltg**

### CODE REVIEW

**Comment by timholy** [comment]
Let's see if CI has been fixed by https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/540

**Review by timholy — APPROVED** [review]

**Comment by t-bltg** [comment]
Yes, nightly ... is nightly :shrug:, expected to break all the time. Thanks for the invite to collaborate on `Revise.jl` btw.

This is only a moderate increase in coverage, but any step towards 100% is good to take I guess.

**Comment by timholy** [comment]
Feel free to merge at will!

**Comment by t-bltg** [comment]
`With great power comes great responsibility` ;)

**Comment by timholy** [comment]
That sentiment is a prerequisite :-)

**Pull request merged**
