### PR TITLE
Circumvent CI hang on 1.8

### PR DESCRIPTION
**Pull request by timholy**
#710 attempted to debug a Requires-based hang that seems
to only occur on CI with Julia 1.8. It may be due to lock contention,
but the precise cause was not obvious.

This just disables the problematic test.
Since it doesn't happen on nightly, and since Requires will be
supplanted by the new weakdeps mechanism, we can direct any
users who encounter this bug to the alternatives.

### CODE REVIEW

**Comment by timholy** [comment]
CC @t-bltg

**Comment by timholy** [comment]
These failures are different and will be fixed by #561. Looks like I pushed this just a few minutes before a new JuliaInterpreter was registered.

**Comment by t-bltg** [comment]
Yes, it's probably best if we can move forward, and rework if we encounter a real case scenario bug related to this.

> Looks like I pushed this just a few minutes before a new JuliaInterpreter was registered.

Let's rerun ci ?

**Comment by timholy** [comment]
This does not seem to be a regression, so let's merge.

**Pull request merged**
