### PR TITLE
scan for the right .ji file containing the target uuid

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by timholy** [comment]
Just to check, the main change here is checking that the UUID matches that provided by `Base.module_uuid`. Seems like a good thing to do. Once it gets through CI, merge at will.

**Comment by vtjnash** [comment]
Yeah (much easier to see if you add `?w=1` to the url

**Comment by timholy** [comment]
Sounds good. Merge whenever you're ready.

**Comment by timholy** [comment]
Is this ready to merge?

**Comment by vtjnash** [comment]
Yes

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
