### PR TITLE
test: hanging `1.8` ci

### PR DESCRIPTION
**Pull request by t-bltg**
Test reverting https://github.com/timholy/Revise.jl/pull/679, in order to determine if it is the cause of `1.8.1` failures / hang in ci.
Tests on master are passing locally on `1.8.1`.
They should take around ~3min, but hang in CI (~6h).

1.8.1 ✘ (master):
https://github.com/timholy/Revise.jl/actions/runs/3055718432/jobs/4940473518

1.7.3 (previous commit, without pr) ✔:
https://github.com/timholy/Revise.jl/actions/runs/2767526837/jobs/4349142764

### CODE REVIEW

**Comment by t-bltg** [comment]
It seems that the PR is not to blame, and that the hang is related to the julia `1`: `1.7.3` -> `1.8.1` in workflows.

**Comment by t-bltg** [comment]
The test hangs at `@eval using RoundingIntegers` in https://github.com/timholy/Revise.jl/blob/3b2275c90106e34d63bc7f67b2edbc5724489bd9/test/runtests.jl#L3147.

**Comment by t-bltg** [comment]
And further investigation shows that it hangs here https://github.com/timholy/Revise.jl/blob/3b2275c90106e34d63bc7f67b2edbc5724489bd9/test/runtests.jl#L3101

**Comment by timholy** [comment]
Closed by #722

**Pull request closed without merging**
