### PR TITLE
Integrate with CodeTracking

### PR DESCRIPTION
**Pull request by timholy**
This sets up [CodeTracking.jl](https://github.com/timholy/CodeTracking.jl) as the new "query interface" of Revise.

### CODE REVIEW

**Comment by oxinabox** [comment]
I am now using this branch and it is (so far) working for me. <3

**Comment by timholy** [comment]
> It would be cool if you could push your CodeTracking.jl branch at the sametime you push to this branch. Alternatively I could just be patient.

There's a pretty complicated dance going on right now with this branch, #243, and work in JuliaInterpreter (e.g., https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/88). I fear you're going to have to expect some breakage for a little while yet.

Some more breaking changes are coming. I need `method_at(file, lineno)` for work in JuliaInterpreter, and that will likely change the internal representation that Revise and/or CodeTracking use.

**Comment by timholy** [comment]
But it should be working as of this moment :smile:

**Comment by timholy** [comment]
The most recent commit requires https://github.com/timholy/CodeTracking.jl/pull/11

**Pull request merged**
