### PR TITLE
RFC: build backedges in the lowered code

### PR DESCRIPTION
**Pull request by timholy**
Here the goal is to figure out which statements need to be executed and which can be ignored. Also takes a step twoards resolving issue #249.

### CODE REVIEW

**Comment by timholy** [comment]
This appears to be working now. It may have *major* peformance benefits (after compilation, which will be slower than ever...) and likely fixes the following issues:
- better fix for #300 (CC @helgee), meaning that putting "work" in `__init__` should no longer be necessary
- #326 (CC @garrison)
- #363 (CC @cstjean)
- #364 (CC @musm)
- possibly #373 (CC @AzamatB)
- definitely fixes #378 (CC @Keno, @vchuravy)
- possibly #379  (CC @kescobo)

I'd appreciate folks checking out this branch, testing, and reporting back! This is a scary change---Revise will no longer even look at certain kinds of code. But hopefully it will avoid looking at precisely the kind of code that has been causing trouble.

**Comment by cstjean** [comment]
In one of my thornier macros, upon revision I get:

```julia
MethodError: no method matching eval_rhs(::typeof(JuliaInterpreter.finish_and_return!), ::JuliaInterpreter.Frame, ::Bool)
Closest candidates are:
  eval_rhs(::Any, ::Any, ::Expr) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:361
Stacktrace:
 [1] lookup_or_eval(::Any, ::JuliaInterpreter.Frame, ::Any) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:111
 [2] lookup_or_eval(::Any, ::JuliaInterpreter.Frame, ::Any) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:89
 [3] evaluate_structtype(::Any, ::JuliaInterpreter.Frame, ::Expr) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:297
 [4] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:464
 [5] step_expr! at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:557 [inlined]
 [6] next_until!(::Any, ::Any, ::JuliaInterpreter.Frame, ::Bool) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/commands.jl:95
 [7] through_methoddef_or_done! at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/commands.jl:147 [inlined]
 [8] top-level scope at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:504 [inlined]
 [9] top-level scope at ./REPL[5]:0
 [10] eval at ./boot.jl:330 [inlined]
 [11] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /home/cst-jean/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:499
 [12] #methods_by_execution!#20(::Bool, ::Bool, ::typeof(Revise.methods_by_execution!), ::Any, ::Revise.CodeTrackingMethodInfo, ::Dict{Module,Array{Expr,1}}, ::JuliaInterpreter.Frame, ::BitArray{1}) at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/lowered.jl:283
 [13] #methods_by_execution! at ./bitarray.jl:0 [inlined]
 [14] #methods_by_execution!#15(::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Revise.methods_by_execution!), ::Any, ::Revise.CodeTrackingMethodInfo, ::Dict{Module,Array{Expr,1}}, ::Module, ::Expr) at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/lowered.jl:103
 [15] #methods_by_execution! at ./none:0 [inlined]
 [16] #eval_with_signatures#71 at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:383 [inlined]
 [17] eval_with_signatures at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:381 [inlined]
 [18] (::getfield(Revise, Symbol("##67#68")){OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}},OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}},Module})() at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:295
 [19] with_logstate(::getfield(Revise, Symbol("##67#68")){OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}},OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}},Module}, ::Base.CoreLogging.LogState) at ./logging.jl:395
 [20] with_logger at ./logging.jl:491 [inlined]
 [21] eval_new! at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:285 [inlined]
 [22] eval_new!(::OrderedCollections.OrderedDict{Module,OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}}, ::OrderedCollections.OrderedDict{Module,OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}}) at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:338
 [23] revise() at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:592
 [24] revise at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:616 [inlined]
 [25] run_backend(::REPL.REPLBackend) at /home/cst-jean/.julia/packages/Revise/0L9Pt/src/Revise.jl:1019
 [26] (::getfield(Revise, Symbol("##88#90")){REPL.REPLBackend})() at ./task.jl:268
```

I can't guarantee that I didn't have that issue before. I'll see if I find the time to isolate it later this week, if necessary?

**Comment by timholy** [comment]
It's a bit unlikely that this was triggered by this branch, since the main thing this branch does is use JuliaInterpreter less (and the error comes from JuliaInterpreter). But I am grateful for the bug report. If you have time, can you `dev JuliaInterpreter` and then try this diff:
```diff
diff --git a/src/interpret.jl b/src/interpret.jl
index 7567b9f..b7b58b9 100644
--- a/src/interpret.jl
+++ b/src/interpret.jl
@@ -79,8 +79,6 @@ function lookup_or_eval(@nospecialize(recurse), frame, @nospecialize(node))
         return lookup_var(frame, node)
     elseif isa(node, Symbol)
         return getfield(moduleof(frame), node)
-    elseif isa(node, Int)
-        return node
     elseif isa(node, QuoteNode)
         return node.value
     elseif isa(node, Expr)
@@ -105,6 +103,8 @@ function lookup_or_eval(@nospecialize(recurse), frame, @nospecialize(node))
             dump(ex)
             error("unknown expr ", ex)
         end
+    elseif isa(node, Number)   # slow, requires subtyping
+        return node
     elseif isa(node, Type)
         return node
     end
```

**Comment by cstjean** [comment]
That diff fixes the bug, but with this branch it still takes 5 minutes (and counting...) to revise one of my files which is nothing but a big macro expansion.

**Comment by kescobo** [comment]
Is using this branch as simple as `]add Revise#backedges`?

**Comment by timholy** [comment]
```julia
pkg> add Revise#teh/backedges
```
(don't forget the `teh/`)

**Comment by kescobo** [comment]
No dice on #379 :-(

**Comment by timholy** [comment]
Bummer. OK, I'll try to figure out the installation.

**Pull request merged**
