### PR TITLE
Some logo graphics

### PR DESCRIPTION
**Pull request by cormullion**
Addressing #405 - I couldn't make a decision, so went with this. The logo is at least square now... :) 

`docs/src/assets/logo.png` is a copy of ` images/revise-logo.png`, etc, so you could tidy this up one day, but for now it's clear that "logo" is the square one, and "wordmark" is the banner, including the logo, as seen in the README.

Scrappy source is [here](https://gist.github.com/cormullion/eb742ccf31e4c1e4f7c0df0060dd8f31) but don't look unless you're morbidly curious... :)

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for this wonderful gift!

Do I need to do anything to get this submitted to the JuliaLang page?

**Comment by cormullion** [comment]
Thank you for letting me play! 

I can transfer it  - but I will wait a few days until the site's been transferred to the new Hugo version.

**Comment by timholy** [comment]
Is it safe now? I haven't been keeping track.

**Comment by cormullion** [comment]
I'll ask...

**Comment by cormullion** [comment]
Thanks to the amazing and omnipresent Logan, it's added.

**Pull request merged**
