### PR TITLE
Create a logo

### PR DESCRIPTION
**Pull request by timholy**
I am considering adding Revise to the "Editors and ~~IDEs~~Development Environment" section of https://julialang.org/; for that to happen and for it to fit in with the others, Revise would need a logo. See https://github.com/timholy/Revise.jl/blob/teh/splash/images/logo.png if you want to see what this candidate logo looks like.

Thoughts? CC @ViralBShah, @StefanKarpinski.

### CODE REVIEW

**Comment by ViralBShah** [comment]
The logo link does not work. I see there's a logo up there, but I usually ping @cormullion for logos. :-)

**Comment by timholy** [comment]
Did not know about @cormullion's many talents!

**Comment by timholy** [comment]
That branch got deleted, now you can see it on the home page https://github.com/timholy/Revise.jl

**Comment by ViralBShah** [comment]
Yes! The DynamicalSystems.jl one is one of my favourties.

https://github.com/JuliaDynamics/DynamicalSystems.jl

**Pull request merged**
