### PR TITLE
implement revise_file_queued for FreeBSD

### LINKED ISSUE #66: Behaviour of watch_file on FreeBSD is different
https://github.com/timholy/Revise.jl/blob/5754f39e17133b384913a7d05a44f377fcc174a6/src/Revise.jl#L188-L200

On FreeBSD modifying a existed file which located at `dir` will not being caught by `watch_dir(dir)`.

### PR DESCRIPTION
**Pull request by iblis17**
fix #66 

---

Basic functionality works for me, but I cannot get test passed :p

### CODE REVIEW

**Comment by timholy** [comment]
Now that I have tests passing on nightly, is there a plausible way to run this through CI?

**Comment by iblis17** [comment]
I rebased and ran it at local. It passed!

**Comment by timholy** [comment]
That's great. I can merge this as-is, and if you want we can think about whether it's possible to set up FreeBSD CI testing for Revise.

**Comment by timholy** [comment]
Many thanks for fixing this!

**Pull request merged**
