### PR TITLE
Prevent double-evaluation in `includet`

### LINKED ISSUE #263: Revise.track reincludes the file (2.0.4 vs 1.1.0)
When using Revise v2, `Revise.track` reincludes the file which was already included via `include`. 

The same thing happens when using `includet`, the file will be included twice when using v2. 

A simple example, if we have two files, `main.jl` and `first.jl`: 

```julia
# main.jl
using Pkg
pkg"activate ."

using Revise

# include("first.jl")
# Revise.track("first.jl")

Revise.includet("first.jl")
```

```julia
# first.jl
println("first")
```

Running `$ julia main.jl` will output 
`first` 
on Revise 1 and 
`first`
`first`
on Revise 2. 

The behaviour is the same if you uncomment the commented lines and comment out the `includet`.

This is no bueno as it loads some of my big files twice, redefines constants and modules, etc.

### PR DESCRIPTION
**Pull request by timholy**
This fixes #263 and also updates to JuliaInterpreter 0.4. Also addresses the TODO item in #258 and fixes a missed aspect of #254.

CC @essenciary

### CODE REVIEW

**Comment by KristofferC** [comment]
Should you relax the `JuliaInterpreter 0.2 0.4` bounds in REQUIRE, which is `[0.2, 0.4)`.

**Comment by timholy** [comment]
Already part of this PR?

**Comment by timholy** [comment]
Hmm, the OSX failure on 1.0 is worrisome. I don't have a suitable machine for testing, anyone out there willing to debug it?

**Comment by KristofferC** [comment]
Sorry, I deleted my comment after I realized I missed it.

For reference: It said that JuliaInterpreter upper bound in REQUIRE needed bumping

**Comment by timholy** [comment]
> Hmm, the OSX failure on 1.0 is worrisome.

Ah, it seems intermittent. I was worried because it happen on both instances, but I reran one of them and it's passing. So I'll merge this as-is; anyone willing to help understand what makes it flaky would have my gratitude.

**Comment by KristofferC** [comment]
Passed locally with:

```
┌ Warning: /Applications/Julia-1.0.app/Contents/Resources/julia/share/julia/base_functions.jl is not a file, omitting from revision tracking
└ @ Revise ~/.julia/packages/Revise/OcHNd/src/parsing.jl:24
┌ Warning: Failed to revise /Applications/Julia-1.0.app/Contents/Resources/julia/share/julia/base/../base_functions.jl: MethodError(convert, (OrderedCollections.OrderedDict{Module,OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}}, nothing), 0x000000000000639b)
└ @ Revise ~/.julia/packages/Revise/OcHNd/src/Revise.jl:539
┌ Warning: skipping git tests because Revise is not under development
└ @ Main ~/.julia/packages/Revise/OcHNd/test/runtests.jl:1546

...

┌ Warning: /Applications/Julia-1.0.app/Contents/Resources/julia/share/julia/stdlib/v1.0/REPLMode.jl is not a file, omitting from revision tracking
└ @ Revise ~/.julia/packages/Revise/OcHNd/src/parsing.jl:24
┌ Warning: Failed to revise /Applications/Julia-1.0.app/Contents/Resources/julia/share/julia/stdlib/v1.0/REPL/../REPLMode.jl: MethodError(convert, (OrderedCollections.OrderedDict{Module,OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}}, nothing), 0x00000000000063d9)

...

	┌ Warning: Replacing docs for `LibGit2.Consts.GIT_CONFIG :: Union{}` in module `LibGit2.Consts`
```

**Comment by timholy** [comment]
Does it always pass if you run it several times? (You have to exit the session and start again, all the modules are already defined so you need to start fresh.)

**Comment by KristofferC** [comment]
Passed 3 times in a row at least.

**Comment by timholy** [comment]
OK, thanks for checking! I'll pass it off as an oddity of Travis. I am pretty sure I've seen this specific failure on other PRs, but this is the first time it failed on both instances.

**Pull request merged**
