### PR TITLE
Check CI on master

### PR DESCRIPTION
**Pull request by IanButterworth**

### CODE REVIEW

**Comment by timholy** [comment]
xref https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/560

**Comment by KristofferC** [comment]
Let's rerun after https://github.com/JuliaRegistries/General/pull/74784

**Comment by timholy** [comment]
Note that we'll get some hangs, see #722. But those shouldn't affect nightly.

**Comment by timholy** [comment]
This won't be necessary, more changes coming.

**Pull request closed without merging**
