### PR TITLE
update to LoweredCodeUtils@2.0.0

### PR DESCRIPTION
**Pull request by aviatesk**
xref: https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/62

### CODE REVIEW

**Comment by aviatesk** [comment]
@timholy (/cc @KristofferC ) Could you please merge this ? 
The current version specification `LoweredCodeUtils = "1.2.8"` allows LoweredCodeUtils@1.3.0, which is not compatible with the current master, so I think we need to tag a new version of Revise.

**Comment by aviatesk** [comment]
@KristofferC can you help me with this ? I'd like to ask you to merge this PR after I merge https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/64.
(I've not heard from Tim these days 😟)

**Comment by aviatesk** [comment]
@KristofferC bump

**Comment by KristofferC** [comment]
@aviatesk Yes I can do that.

**Pull request merged**
