### PR TITLE
try figure out why Travis passed a buggy PR [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by timholy** [comment]
Good idea, I should have tried that myself...

**Comment by KristofferC** [comment]
Hmm, seems to pass here as well.

**Comment by KristofferC** [comment]
Okay, it isn't stranger than that this branch is not taken:

https://github.com/timholy/Revise.jl/blob/66380df2499700a8af6719f84b4562e74aa3219a/src/pkgs.jl#L98

**Comment by timholy** [comment]
Ah, very good! Thanks for figuring that out.

**Comment by timholy** [comment]
xref #465

**Pull request closed without merging**
