### PR TITLE
allow CI nightly to fail so badge is green

### PR DESCRIPTION
**Pull request by Moelf**
There are two ways of doing this, another possibility is to have a separate `ci_nightly.yml`, let me know if maintainers prefer that route.

### CODE REVIEW

**Comment by timholy** [comment]
The issue is that this failure is going to be on all Julia versions starting with 1.10, so making an exception for nightly soon won't help anything. We just have to fix the test failures.

**Comment by Moelf** [comment]
but this would be useful for future future? I think it's a general idea to not show red CI badge for Nightly

**Comment by timholy** [comment]
Fair enough!

**Comment by timholy** [comment]
Hmm, the badge is still red even though only nightly is failing.

**Comment by Moelf** [comment]
I wonder if this is correct https://github.com/timholy/Revise.jl/blob/9f7bd4ea3d7b2c3bd37e64130abb718aba2a8072/README.md?plain=1#L3C49-L3C49

**Comment by timholy** [comment]
If I try updating it with
```
[![CI](https://github.com/timholy/Revise.jl/actions/workflows/ci.yml/badge.svg)](https://github.com/timholy/Revise.jl/actions/workflows/ci.yml)
```
(the text supplied by the "Create Status Badge" option, it still shows red.

**Comment by Moelf** [comment]
ah, we need this line https://github.com/JuliaHEP/UnROOT.jl/blob/77b75d8f8a7d5a6a2b8c408efbcac2c00817e798/.github/workflows/ci.yml#L14C1-L14C51

**Pull request merged**
