### PR TITLE
tweak for upcoming `Core.Compiler` change

### PR DESCRIPTION
**Pull request by aviatesk**
https://github.com/JuliaLang/julia/pull/43800 will define new module `EscapeAnalysis`
inside `Core.Compiler`, and it requires this minor special handling.

### CODE REVIEW

**Comment by aviatesk** [comment]
Please do not merge this until we merge #43800.

**Comment by pfitzseb** [comment]
Should this just check for `isdefined(Core.Compiler, :EscapeAnalysis)`?

**Comment by aviatesk** [comment]
Right, we should have that static check also.

**Review by timholy — APPROVED** [review]

**Comment by ianatol** [comment]
@timholy Can this be merged? Revise is broken on master without it

**Comment by timholy** [comment]
@aviatesk do you want to make the new release? Just in case you know stuff that needs changing before we do that. I'm not running on the very latest master as I continue to work on getting https://github.com/JuliaLang/julia/pull/43990 over the finish line.

**Comment by aviatesk** [comment]
It seems like JuliaInterpreter needs a bit more update to work on 1.8. We should probably wait for it to be updated before making the new release of Revise.

**Comment by aviatesk** [comment]
@timholy Now Revise test suite runs successfully both on 1.7 and the very latest master, I'd like to ask you to publish the new release (maybe the patch one)?

**Comment by timholy** [comment]
I don't know why CI is hanging on nightly, but I did just check that it works locally, so I'll tag.

**Pull request merged**
