### PR TITLE
do a little bit of work to try confirm that the git repo found is actually a julia repo before running `Core.Compiler` test

### LINKED ISSUE #834: Test error when testing Revise on buildkite
In order to not make Revise break all the time on master it would be a good idea to test it together with Julia CI so fixes can be more proactive. 

https://github.com/JuliaCI/julia-buildkite/pull/372 adds such a test, however, the tests fail (https://buildkite.com/julialang/julia-buildkite/builds/1635#01910896-70f5-482d-bce9-c5cf16132e41) with:

```
Recipes: Error During Test at /root/.julia/packages/Revise/uvGMC/test/runtests.jl:2840
  Got exception outside of a @test
  KeyError: key Base.PkgId(nothing, "Core") not found
  Stacktrace:
    [1] getindex(h::Dict{Base.PkgId, Revise.PkgData}, key::Base.PkgId)
      @ Base ./dict.jl:477
    [2] top-level scope
      @ ~/.julia/packages/Revise/uvGMC/test/runtests.jl:78
    [3] macro expansion
      @ /cache/build/builder-amdci5-3/julialang/julia-buildkite/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1703 [inlined]
    [4] macro expansion
      @ ~/.julia/packages/Revise/uvGMC/test/runtests.jl:2842 [inlined]
    [5] macro expansion
      @ /cache/build/builder-amdci5-3/julialang/julia-buildkite/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1703 [inlined]
    [6] macro expansion
      @ ~/.julia/packages/Revise/uvGMC/test/runtests.jl:2887 [inlined]
    [7] include(fname::String)
      @ Main ./sysimg.jl:38
    [8] top-level scope
      @ none:6
    [9] eval
      @ ./boot.jl:438 [inlined]
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:290
   [11] _start()
      @ Base ./client.jl:551
```

It's not clear to me why the tests should fail there but not on the GHA runner used in this repo.

### PR DESCRIPTION
**Pull request by KristofferC**
Try to fix #834. Will confirm on buildkite.

### CODE REVIEW

**Comment by KristofferC** [comment]
So while I think it is an improvement, it seems that in buildkite we actually reach a julia repo that comes from somewhere..

https://buildkite.com/julialang/julia-buildkite/builds/1646#01910d9b-e1b1-4e5b-a1af-bf4ffea85858/623-675

```
readdir((Revise.git_repo(Revise.juliadir))[2]) = [".buildkite", ".buildkite-external-version", ".clang-format", ".clangd", ".codecov.yml", ".devcontainer", ".git", ".git-blame-ignore-revs", ".gitattributes", ".github", ".gitignore", ".mailmap", "CITATION.bib", "CITATION.cff", "CONTRIBUTING.md", "HISTORY.md", "LICENSE.md", "Make.inc", "Makefile", "NEWS.md", "README.md", "THIRDPARTY.md", "VERSION", "base", "cli", "contrib", "deps", "doc", "etc", "julia", "julia-df1976d500-linux-x86_64.tar.gz", "julia.spdx.json", "pkgimage.mk", "src", "stdlib", "sysimage.mk", "test", "typos.toml", "usr"]
```

**Comment by KristofferC** [comment]
@timholy, can I just disable this test on CI (when env var `CI` is set)? It would be good to get https://github.com/JuliaCI/julia-buildkite/pull/372 through but I am running out of steam to try to make Revise realize that it shouldn't run this test in this case.

**Comment by timholy** [comment]
Is there any way we can make it buildkite-specific? If not, the plan to trigger it on `CI` seems reasonable.

**Comment by KristofferC** [comment]
> Is there any way we can make it buildkite-specific?

Yes, I did that now

**Pull request merged**
